[package]
name = "rlisp-repl"
version = "0.1.0"
authors = ["Zaiyang Li <zaiyang@cloudflare.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rlisp = { path = "../rlisp" }